name: "Update Packages & Nix flake lock"

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "15 22 * * 4" # runs every Thursday at 22:15 UTC

jobs:
  update:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: ./.github/actions/install-nix
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: fym998/update-flake-lock@dogfood
        id: update-flake-lock
        with:
          pr-title: "[Automated] Update Packages & Nix flake lock"
          flakes: |
            flake-modules/_internal/dev
            .
      - run: nix run .#_update -- --commit --skip-prompt --keep-going
