name: "Auto fetch Erlang"
on:
  push:
    paths-ignore:
      - .gitignore
      - README.md
  schedule:
    # rebuild everyday at 2:51
    # TIP: Choose a random time here so not all repositories are build at once:
    # https://www.random.org/clock-times/?num=1&earliest=01%3A00&latest=08%3A00&interval=5&format=html&rnd=new
    - cron: "05 3 * * *"
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2

      - name: Install nix
        uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7"

      - run: |
          bundle
          bundle exec ruby fetch_erlang_releases.rb

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: New Erlang releases
          author: Jechol Lee <mr.jechol@gmail.com>
          branch: auto-erlang
          title: "New Erlang releases"
          body: |
            New releases added.

            Add default.nix if new folder is created.
          labels: |
            auto-pr
          assignees: jechol
          reviewers: jechol
