[windows10-icons]
src.github = "B00merang-Artwork/Windows-10"
fetch.github = "B00merang-Artwork/Windows-10"

[windows10-themes]
src.github = "B00merang-Project/Windows-10"
fetch.github = "B00merang-Project/Windows-10"

[undollar]
src.github = "Freed-Wu/undollar"
fetch.github = "Freed-Wu/undollar"

[manpager]
src.github = "Freed-Wu/manpager"
fetch.github = "Freed-Wu/manpager"

[repl-python-wakatime]
src.pypi = "repl-python-wakatime"
fetch.pypi = "repl-python-wakatime"

[translate-shell]
src.pypi = "translate-shell"
fetch.pypi = "translate-shell"

[lsp-tree-sitter]
src.pypi = "lsp-tree-sitter"
fetch.pypi = "lsp-tree-sitter"

[autotools-language-server]
src.pypi = "autotools-language-server"
fetch.pypi = "autotools-language-server"

[expect-language-server]
src.pypi = "expect-language-server"
fetch.pypi = "expect-language-server"

[mutt-language-server]
src.pypi = "mutt-language-server"
fetch.pypi = "mutt-language-server"

[requirements-language-server]
src.pypi = "requirements-language-server"
fetch.pypi = "requirements-language-server"

[sublime-syntax-language-server]
src.pypi = "sublime-syntax-language-server"
fetch.pypi = "sublime-syntax-language-server"

[termux-language-server]
src.pypi = "termux-language-server"
fetch.pypi = "termux-language-server"

[tmux-language-server]
src.pypi = "tmux-language-server"
fetch.pypi = "tmux-language-server"

[tree-sitter-muttrc]
src.pypi = "tree-sitter-muttrc"
fetch.pypi = "tree_sitter_muttrc"

[tree-sitter-tmux]
src.pypi = "tree-sitter-tmux"
fetch.pypi = "tree_sitter_tmux"

[tree-sitter-zathurarc]
src.pypi = "tree-sitter-zathurarc"
fetch.pypi = "tree_sitter_zathurarc"

[tree-sitter-requirements]
src.github_tag = "tree-sitter-grammars/tree-sitter-requirements"
fetch.github = "tree-sitter-grammars/tree-sitter-requirements"

[tree-sitter-languages]
src.github_tag = "grantjenks/py-tree-sitter-languages"
fetch.github = "grantjenks/py-tree-sitter-languages"

[xilinx-language-server]
src.pypi = "xilinx-language-server"
fetch.pypi = "xilinx-language-server"

[zathura-language-server]
src.pypi = "zathura-language-server"
fetch.pypi = "zathura-language-server"

[mulimgviewer]
src.pypi = "mulimgviewer"
fetch.pypi = "mulimgviewer"
