[windows10-themes]
src.github = "B00merang-Project/Windows-10"
fetch.github = "B00merang-Project/Windows-10"

[undollar]
src.github = "Freed-Wu/undollar"
fetch.github = "Freed-Wu/undollar"

[manpager]
src.github = "Freed-Wu/manpager"
fetch.github = "Freed-Wu/manpager"

[translate-shell]
src.pypi = "translate-shell"
fetch.pypi = "translate_shell"

[expect-language-server]
src.pypi = "expect-language-server"
fetch.pypi = "expect-language-server"

[xilinx-language-server]
src.pypi = "xilinx-language-server"
fetch.pypi = "xilinx-language-server"

[sublime-syntax-language-server]
src.pypi = "sublime-syntax-language-server"
fetch.pypi = "sublime-syntax-language-server"

[mutt-language-server]
src.pypi = "mutt-language-server"
fetch.pypi = "mutt_language_server"

[requirements-language-server]
src.pypi = "requirements-language-server"
fetch.pypi = "requirements_language_server"

[termux-language-server]
src.pypi = "termux-language-server"
fetch.pypi = "termux_language_server"

[tmux-language-server]
src.pypi = "tmux-language-server"
fetch.pypi = "tmux_language_server"

[zathura-language-server]
src.pypi = "zathura-language-server"
fetch.pypi = "zathura_language_server"

[tree-sitter-muttrc]
src.pypi = "tree-sitter-muttrc"
fetch.pypi = "tree_sitter_muttrc"

[tree-sitter-tmux]
src.pypi = "tree-sitter-tmux"
fetch.pypi = "tree_sitter_tmux"

[tree-sitter-zathurarc]
src.pypi = "tree-sitter-zathurarc"
fetch.pypi = "tree_sitter_zathurarc"

[tree-sitter-requirements]
src.github_tag = "tree-sitter-grammars/tree-sitter-requirements"
fetch.github = "tree-sitter-grammars/tree-sitter-requirements"

# https://github.com/tree-sitter/tree-sitter-bash/issues/281
[tree-sitter-bash]
src.github_tag = "tree-sitter/tree-sitter-bash"
fetch.github = "tree-sitter/tree-sitter-bash"

[mulimgviewer]
src.pypi = "mulimgviewer"
fetch.pypi = "mulimgviewer"

[clipman]
src.pypi = "clipman"
fetch.pypi = "clipman"

[pyrime]
src.pypi = "pyrime"
fetch.pypi = "pyrime"

[bash-prompt]
src.github_tag = "Freed-Wu/bash-prompt"
fetch.github = "Freed-Wu/bash-prompt"
