[[host]]
name = "hastur" # homeserver censored
addr = "riro@10.0.4.2"

[[host]]
name = "kaambl" # laptop
addr = "elen@10.0.1.3"

[[host]]
name = "abhoth" # vmiss
addr = "elen@38.47.119.151"

[[host]]
name = "azasos" # tencent cloud censored
addr = "elen@116.196.112.43"

[[host]]
name = "eihort" # nas
addr = "elen@10.0.1.6"

[[host]]
name = "nodens" # digital ocean sf
addr = "elen@144.126.208.183"

[[host]]
name = "yidhra" # feral chicken
addr = "elen@8.210.47.13"
