[claudecode-nvim]
src.git = "https://github.com/coder/claudecode.nvim"
src.branch = "main"
fetch.github = "coder/claudecode.nvim"

[copyq-darwin]
src.github = "hluk/CopyQ"
src.prefix = "v"
fetch.url = "https://github.com/hluk/CopyQ/releases/download/v$ver/CopyQ-macos-12-m1.dmg.zip"

[emacs-plus]
src.git = "https://github.com/d12frosted/homebrew-emacs-plus"
src.branch = "master"
fetch.github = "d12frosted/homebrew-emacs-plus"

[hammerspoon]
src.github = "Hammerspoon/hammerspoon"
fetch.url = "https://github.com/Hammerspoon/hammerspoon/releases/download/$ver/Hammerspoon-$ver.zip"

[nixpkgs-review]
src.git = "https://github.com/natsukium/nixpkgs-review"
src.branch = "develop"
fetch.github = "natsukium/nixpkgs-review"

[paperwm-spoon]
src.git = "https://github.com/mogenson/PaperWM.spoon"
src.branch = "main"
fetch.github = "mogenson/PaperWM.spoon"

[qmk-toolbox]
src.github = "qmk/qmk_toolbox"
fetch.url = "https://github.com/qmk/qmk_toolbox/releases/download/$ver/QMK.Toolbox.app.zip"

[qutebrowser-darwin]
src.github = "qutebrowser/qutebrowser"
src.prefix = "v"
fetch.url = "https://github.com/qutebrowser/qutebrowser/releases/download/v$ver/qutebrowser-$ver-arm64.dmg"

[sbarlua]
src.git = "https://github.com/FelixKratz/SbarLua"
src.branch = "main"
fetch.github = "FelixKratz/SbarLua"

[skills-ref]
src.git = "https://github.com/agentskills/agentskills"
src.branch = "main"
fetch.github = "agentskills/agentskills"

[skkeleton]
src.git = "https://github.com/vim-skk/skkeleton"
src.branch = "main"
fetch.github = "vim-skk/skkeleton"

[vivaldi-darwin]
src.archpkg = "vivaldi"
fetch.url = "https://downloads.vivaldi.com/stable/Vivaldi.$ver.universal.dmg"

[zen-browser]
src.github = "zen-browser/desktop"
fetch.url = "https://github.com/zen-browser/desktop/releases/download/$ver/zen.macos-universal.dmg"
