name: Auto Bump Trigger

on:
  schedule:
    - cron: "0 16 * * *"

  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Calculate bumpNumber
        id: calc
        run: |
          DATE=$(date +%Y%m%d)
          COUNT=$(git ls-remote --heads https://github.com/lonerOrz/nyx-loner.git "refs/heads/bump/$DATE-" | wc -l)
          BUMP=$((COUNT + 1))
          echo "bumpNumber=$BUMP" >> "$GITHUB_OUTPUT"

      - name: Trigger upstream auto-bump workflow
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/lonerOrz/nyx-loner/actions/workflows/auto-bump.yml/dispatches \
            -d "{
              \"ref\": \"main\",
              \"inputs\": {
                \"bumpNumber\": \"${{ steps.calc.outputs.bumpNumber }}\"
              }
            }"
