language: nix
nix: 2.3.2

before_install:
  - ./ci/configure-nix.sh
  - ./ci/install-cachix.sh
  - ./ci/launch-cachix.sh

env:
  global:
    - CACHIX_CACHE=allvm
    - NUR_REPO=dtz
  matrix:
    - NIX_PATH=nixpkgs=channel:nixos-unstable
    - NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz

before_script:
  - nix run nixpkgs.nix-info -c nix-info -m

script:
  - nix-build ./ci --arg nixpkgs '<nixpkgs>' -A pkgs

after_script:
  - ./ci/push.sh ./result*

# Force VM instead of container, so that sandbox works
sudo: required

# Full clone, so 'fetchGit' works
git:
  depth: false
