[acpi-ec]
src.github = "musikid/acpi_ec"
fetch.github = "musikid/acpi_ec"

[amule-dlp]
src.git = "https://github.com/persmule/amule-dlp.git"
fetch.github = "persmule/amule-dlp"

[asterisk-alaw16]
src.git = "https://github.com/traud/asterisk-alaw16.git"
fetch.github = "traud/asterisk-alaw16"

[asterisk-amr]
src.git = "https://github.com/traud/asterisk-amr.git"
fetch.github = "traud/asterisk-amr"

[asterisk-evs]
src.git = "https://github.com/traud/asterisk-evs.git"
fetch.github = "traud/asterisk-evs"

[asterisk-g72x]
src.git = "https://github.com/arkadijs/asterisk-g72x.git"
fetch.github = "arkadijs/asterisk-g72x"

[asterisk-gsm-efr]
src.git = "https://github.com/traud/asterisk-gsm-efr.git"
fetch.github = "traud/asterisk-gsm-efr"

[attic]
src.git = "https://github.com/zhaofengli/attic.git"
fetch.github = "zhaofengli/attic"

[baidunetdisk]
src.aur = "baidunetdisk-electron"
src.from_pattern = "(.+)-(.+)"
src.to_pattern = "\\1"
fetch.url = "http://wppkg.baidupcs.com/issue/netdisk/Linuxguanjia/$ver/baidunetdisk_$ver_amd64.deb"

[baidupcs-go]
src.github = "qjfoidnh/BaiduPCS-Go"
fetch.github = "qjfoidnh/BaiduPCS-Go"

[bepasty]
src.pypi = "bepasty"
fetch.pypi = "bepasty"

[bilibili]
src.github_tag = "msojocs/bilibili-linux"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/msojocs/bilibili-linux/releases/download/v$ver/io.github.msojocs.bilibili_$ver_amd64.deb"

[bird-lg-go]
src.github = "xddxdd/bird-lg-go"
fetch.github = "xddxdd/bird-lg-go"

[boringssl-oqs]
src.git = "https://github.com/open-quantum-safe/boringssl.git"
fetch.github = "open-quantum-safe/boringssl"

[cachyos-kernel-patches]
src.git = "https://github.com/CachyOS/kernel-patches"
fetch.github = "CachyOS/kernel-patches"

[calibre-cops]
src.github = "seblucas/cops"
fetch.url = "https://github.com/seblucas/cops/releases/download/$ver/cops-$ver.zip"

[cef-binary]
src.git = "https://github.com/martyr-deepin/cef-binary.git"
fetch.github = "martyr-deepin/cef-binary"

[click-loglevel]
src.pypi = "click-loglevel"
fetch.pypi = "click-loglevel"

[cloudpan189-go]
src.github = "tickstep/cloudpan189-go"
fetch.github = "tickstep/cloudpan189-go"

[cockpy]
src.git = "https://github.com/Hiro420/CockPY.git"
fetch.github = "Hiro420/CockPY"

[cockpy-pyenet]
src.git = "https://github.com/lilmayofuksu/pyenet.git"
fetch.github = "lilmayofuksu/pyenet"
git.fetchSubmodules = true

[coredns-lantian]
src.git = "https://github.com/xddxdd/coredns.git"
fetch.github = "xddxdd/coredns"

[cryptodev-linux]
src.git = "https://github.com/cryptodev-linux/cryptodev-linux.git"
fetch.github = "cryptodev-linux/cryptodev-linux"

[decluttarr]
src.github_tag = "ManiMatter/decluttarr"
fetch.github = "ManiMatter/decluttarr"

[dingtalk]
src.aur = "dingtalk-bin"
fetch.url = "https://dtapp-pub.dingtalk.com/dingtalk-desktop/xc_dingtalk_update/linux_deb/Release/com.alibabainc.dingtalk_$ver_amd64.deb"

[douban-openapi-server]
src.git = "https://github.com/caryyu/douban-openapi-server.git"
fetch.github = "caryyu/douban-openapi-server"

[dpdk-kmod]
src.git = "git://dpdk.org/dpdk-kmods"
fetch.git = "git://dpdk.org/dpdk-kmods"

[drone-file-secret]
src.git = "https://github.com/xddxdd/drone-file-secret.git"
fetch.github = "xddxdd/drone-file-secret"

[drone-vault]
src.github_tag = "drone/drone-vault"
fetch.github = "drone/drone-vault"

[etherguard]
src.git = "https://github.com/KusakabeShi/EtherGuard-VPN.git"
fetch.github = "KusakabeShi/EtherGuard-VPN"

[fastapi-dls]
src.git = "https://git.collinwebdesigns.de/oscar.krause/fastapi-dls.git"
fetch.git = "https://git.collinwebdesigns.de/oscar.krause/fastapi-dls.git"

[fcitx5-breeze]
src.github = "scratch-er/fcitx5-breeze"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/scratch-er/fcitx5-breeze/releases/download/v$ver/fcitx5-breeze-prebuilt-$ver.tar.gz"

[flaresolverr]
src.github = "FlareSolverr/FlareSolverr"
fetch.github = "FlareSolverr/FlareSolverr"

[flasgger]
src.github = "flasgger/flasgger"
fetch.github = "flasgger/flasgger"

[genshin-checkin-helper]
src.git = "https://gitlab.com/y1ndan/genshin-checkin-helper.git"
fetch.git = "https://gitlab.com/y1ndan/genshin-checkin-helper.git"

[genshinhelper2]
src.git = "https://github.com/y1ndan/genshinhelper2.git"
fetch.github = "y1ndan/genshinhelper2"

[glauth]
src.github = "glauth/glauth"
fetch.github = "glauth/glauth"

[google-earth-pro]
src.aur = "google-earth-pro"
fetch.url = "https://dl.google.com/linux/earth/deb/pool/main/g/google-earth-pro-stable/google-earth-pro-stable_$ver-r0_amd64.deb"

[grasscutter]
src.github = "Grasscutters/Grasscutter"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/Grasscutters/Grasscutter/releases/download/v$ver/grasscutter-$ver.jar"

[grasscutter-resources]
src.git = "https://gitlab.com/YuukiPS/GC-Resources.git"
fetch.git = "https://gitlab.com/YuukiPS/GC-Resources.git"

[hoyo-glyphs]
src.git = "https://github.com/SpeedyOrc-C/Hoyo-Glyphs.git"
fetch.github = "SpeedyOrc-C/Hoyo-Glyphs"

[hoyo-glyphs-font-ainee]
src.manual = "1.000"
fetch.url = "https://github.com/SpeedyOrc-C/HoYo-Glyphs/releases/download/font-ainee-1.000/Font-Ainee-1.000.zip"

[hoyo-glyphs-star-rail-neue]
src.manual = "1.100"
fetch.url = "https://github.com/SpeedyOrc-C/HoYo-Glyphs/releases/download/star-rail-neue-1.100/Star-Rail-Neue-1.100.zip"

[hoyo-glyphs-teyvat-black]
src.manual = "1.003"
fetch.url = "https://github.com/SpeedyOrc-C/HoYo-Glyphs/releases/download/teyvat-black-1.003/Teyvat-Black-1.003.zip"

[hoyo-glyphs-xianzhou-seal]
src.manual = "1.000"
fetch.url = "https://github.com/SpeedyOrc-C/HoYo-Glyphs/releases/download/xianzhou-seal-1.000/Xianzhou-Seal-1.000.zip"

[i915-sriov-dkms]
src.git = "https://github.com/strongtz/i915-sriov-dkms.git"
fetch.github = "strongtz/i915-sriov-dkms"

[jproxy]
src.manual = "v3.4.1"
fetch.url = "https://github.com/LuckyPuppy514/jproxy/releases/download/$ver/windows-$ver.zip"

[kata-containers]
src.github_tag = "kata-containers/kata-containers"
src.include_regex = "^[0-9\\.]+$"
fetch.github = "kata-containers/kata-containers"

[kata-image]
src.github_tag = "kata-containers/kata-containers"
src.include_regex = "^[0-9\\.]+$"
fetch.url = "https://github.com/kata-containers/kata-containers/releases/download/$ver/kata-static-$ver-amd64.tar.xz"

[konnect]
src.github_tag = "Kopano-dev/konnect"
fetch.github = "Kopano-dev/konnect"

[ldap-auth-proxy]
src.git = "https://github.com/pinepain/ldap-auth-proxy.git"
fetch.github = "pinepain/ldap-auth-proxy"

[libltnginx]
src.git = "https://github.com/xddxdd/libltnginx.git"
fetch.github = "xddxdd/libltnginx"

[liboqs]
src.git = "https://github.com/open-quantum-safe/liboqs.git"
fetch.github = "open-quantum-safe/liboqs"

[libqcef]
src.git = "https://github.com/martyr-deepin/qcef.git"
fetch.github = "martyr-deepin/qcef"

[librime-charcode]
src.git = "https://github.com/rime/librime-charcode.git"
fetch.github = "rime/librime-charcode"

[librime-lua]
src.git = "https://github.com/hchunhui/librime-lua.git"
fetch.github = "hchunhui/librime-lua"

[librime-octagram]
src.git = "https://github.com/lotem/librime-octagram.git"
fetch.github = "lotem/librime-octagram"

[librime-proto]
src.git = "https://github.com/lotem/librime-proto.git"
fetch.github = "lotem/librime-proto"

[linux-xanmod]
src.github_tag = "xanmod/linux"
fetch.github = "xanmod/linux"

[linux-xanmod-6_6]
src.github_tag = "xanmod/linux"
src.include_regex = "^6\\.6\\.(.*)"
fetch.github = "xanmod/linux"

[linux-xanmod-6_1]
src.github_tag = "xanmod/linux"
src.include_regex = "^6\\.1\\.(.*)"
fetch.github = "xanmod/linux"

[linux-xanmod-6_0]
src.github_tag = "xanmod/linux"
src.include_regex = "^6\\.0\\.(.*)"
fetch.github = "xanmod/linux"

[nbfc-linux-lantian]
src.git = "https://github.com/xddxdd/nbfc-linux.git"
fetch.github = "xddxdd/nbfc-linux"

[netboot-xyz-efi]
src.github = "netbootxyz/netboot.xyz"
fetch.url = "https://github.com/netbootxyz/netboot.xyz/releases/download/$ver/netboot.xyz.efi"

[netboot-xyz-lkrn]
src.github = "netbootxyz/netboot.xyz"
fetch.url = "https://github.com/netbootxyz/netboot.xyz/releases/download/$ver/netboot.xyz.lkrn"

[netns-exec]
src.git = "https://github.com/pekman/netns-exec.git"
fetch.github = "pekman/netns-exec"
git.fetchSubmodules = true

[nft-fullcone]
src.git = "https://github.com/fullcone-nat-nftables/nft-fullcone.git"
fetch.github = "fullcone-nat-nftables/nft-fullcone"

[nginx-module-stream-sts]
src.git = "https://github.com/vozlt/nginx-module-stream-sts.git"
fetch.github = "vozlt/nginx-module-stream-sts"

[nginx-module-sts]
src.git = "https://github.com/vozlt/nginx-module-sts.git"
fetch.github = "vozlt/nginx-module-sts"

[nginx-module-vts]
src.git = "https://github.com/vozlt/nginx-module-vts.git"
fetch.github = "vozlt/nginx-module-vts"

[nginx-njs]
src.github_tag = "nginx/njs"
fetch.github = "nginx/njs"

[ngx_brotli]
# src.git = "https://github.com/google/ngx_brotli.git"
# fetch.github = "google/ngx_brotli"
src.git = "https://github.com/u5surf/ngx_brotli.git"
src.branch = "fix_build_failed"
fetch.github = "u5surf/ngx_brotli"

[noise-suppression-for-voice]
src.github = "werman/noise-suppression-for-voice"
fetch.github = "werman/noise-suppression-for-voice"

[nullfs]
src.git = "https://github.com/xrgtn/nullfs.git"
fetch.github = "xrgtn/nullfs"

[nullfsvfs]
src.github = "abbbi/nullfsvfs"
fetch.github = "abbbi/nullfsvfs"

[oci-arm-host-capacity]
src.git = "https://github.com/hitrov/oci-arm-host-capacity.git"
fetch.github = "hitrov/oci-arm-host-capacity"

[onepush]
src.git = "https://github.com/y1ndan/onepush.git"
fetch.github = "y1ndan/onepush"

[openresty]
src.github = "openresty/openresty"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/openresty/openresty/releases/download/v$ver/openresty-$ver.tar.gz"

[openssl-oqs]
src.git = "https://github.com/open-quantum-safe/openssl.git"
src.branch = "OQS-OpenSSL_1_1_1-stable"
fetch.github = "open-quantum-safe/openssl"

[openssl-oqs-provider]
src.git = "https://github.com/open-quantum-safe/oqs-provider.git"
fetch.github = "open-quantum-safe/oqs-provider"

[osdlyrics]
src.github = "osdlyrics/osdlyrics"
fetch.github = "osdlyrics/osdlyrics"

[ovpn-dco]
src.git = "https://github.com/OpenVPN/ovpn-dco.git"
fetch.github = "OpenVPN/ovpn-dco"

[palworld-exporter]
src.github_tag = "palworldlol/palworld-exporter"
fetch.github = "palworldlol/palworld-exporter"

[palworld-worldoptions]
src.github = "legoduded/palworld-worldoptions"
fetch.github = "legoduded/palworld-worldoptions"

[payload-dumper-go]
src.github = "ssut/payload-dumper-go"
fetch.github = "ssut/payload-dumper-go"

[peerbanhelper]
src.github = "Ghost-chu/PeerBanHelper"
fetch.url = "https://github.com/Ghost-chu/PeerBanHelper/releases/download/$ver/PeerBanHelper.$ver.jar"

[phpmyadmin]
src.github_tag = "phpmyadmin/phpmyadmin"
src.include_regex = "RELEASE_([0-9_]*)"
src.from_pattern = "RELEASE_([0-9])_([0-9])_([0-9])"
src.to_pattern = "\\1.\\2.\\3"
fetch.url = "https://files.phpmyadmin.net/phpMyAdmin/$ver/phpMyAdmin-$ver-all-languages.tar.xz"

[phppgadmin]
src.github = "ReimuHakurei/phppgadmin"
fetch.github = "ReimuHakurei/phppgadmin"

[plangothic-fonts]
src.github = "Fitzgerald-Porthmouth-Koenigsegg/Plangothic"
fetch.github = "Fitzgerald-Porthmouth-Koenigsegg/Plangothic"

[plasma-desktop-lyrics]
src.github = "chiyuki0325/PlasmaDesktopLyrics"
fetch.github = "chiyuki0325/PlasmaDesktopLyrics"

[plasma-panel-transparency-toggle]
src.git = "https://github.com/sanjay-kr-commit/panelTransparencyToggleForPlasma6.git"
fetch.github = "sanjay-kr-commit/panelTransparencyToggleForPlasma6"

[procps4]
src.archpkg = "procps-ng"
fetch.url = "https://sourceforge.net/projects/procps-ng/files/Production/procps-ng-$ver.tar.xz"

[pterodactyl-wings]
src.github = "pterodactyl/wings"
fetch.github = "pterodactyl/wings"

[py-rcon]
src.github_tag = "ttk1/py-rcon"
fetch.github = "ttk1/py-rcon"

[qbittorrent-enhanced-edition]
src.github = "c0re100/qBittorrent-Enhanced-Edition"
fetch.github = "c0re100/qBittorrent-Enhanced-Edition"

[qemu-user-static-amd64]
src.webpage = "https://packages.debian.org/sid/amd64/qemu-user-static/download"
src.regex = "http://ftp.debian.org/debian/pool/main/q/qemu/qemu-user-static_([^\"]+)_amd64.deb"
fetch.url = "http://ftp.debian.org/debian/pool/main/q/qemu/qemu-user-static_$ver_amd64.deb"

[qemu-user-static-arm64]
src.webpage = "https://packages.debian.org/sid/arm64/qemu-user-static/download"
src.regex = "http://ftp.debian.org/debian/pool/main/q/qemu/qemu-user-static_([^\"]+)_arm64.deb"
fetch.url = "http://ftp.debian.org/debian/pool/main/q/qemu/qemu-user-static_$ver_arm64.deb"

[qemu-user-static-armhf]
src.webpage = "https://packages.debian.org/sid/armhf/qemu-user-static/download"
src.regex = "http://ftp.debian.org/debian/pool/main/q/qemu/qemu-user-static_([^\"]+)_armhf.deb"
fetch.url = "http://ftp.debian.org/debian/pool/main/q/qemu/qemu-user-static_$ver_armhf.deb"

[qemu-user-static-i386]
src.webpage = "https://packages.debian.org/sid/i386/qemu-user-static/download"
src.regex = "http://ftp.debian.org/debian/pool/main/q/qemu/qemu-user-static_([^\"]+)_i386.deb"
fetch.url = "http://ftp.debian.org/debian/pool/main/q/qemu/qemu-user-static_$ver_i386.deb"

[qq-amd64]
src.webpage = "https://im.qq.com/rainbow/linuxQQDownload/"
src.regex = "\"https://dldir1.qq.com/qqfile/qq/QQNT/([^\"]+_amd64[^\"]*).deb\""
fetch.url = "https://dldir1.qq.com/qqfile/qq/QQNT/$ver.deb"

[qq-arm64]
src.webpage = "https://im.qq.com/rainbow/linuxQQDownload/"
src.regex = "\"https://dldir1.qq.com/qqfile/qq/QQNT/([^\"]+_arm64[^\"]*).deb\""
fetch.url = "https://dldir1.qq.com/qqfile/qq/QQNT/$ver.deb"

[qqmusic]
src.aur = "qqmusic-bin"
fetch.url = "https://dldir1.qq.com/music/clntupate/linux/deb/qqmusic_$ver_amd64_.deb"

[qsc-key-encoder]
src.git = "https://github.com/Quantum-Safe-Collaboration/qsc-key-encoder.git"
fetch.github = "Quantum-Safe-Collaboration/qsc-key-encoder"

[r8125]
src.github_tag = "awesometic/realtek-r8125-dkms"
fetch.github = "awesometic/realtek-r8125-dkms"

[r8168]
src.github_tag = "mtorromeo/r8168"
fetch.github = "mtorromeo/r8168"

[rime-aurora-pinyin]
src.git = "https://github.com/hosxy/rime-aurora-pinyin.git"
fetch.github = "hosxy/rime-aurora-pinyin"

[rime-dict]
src.git = "https://github.com/Iorest/rime-dict.git"
fetch.github = "Iorest/rime-dict"

[rime-ice]
src.git = "https://github.com/iDvel/rime-ice.git"
fetch.github = "iDvel/rime-ice"

[rime-moegirl]
src.github = "outloudvi/mw2fcitx"
fetch.url = "https://github.com/outloudvi/mw2fcitx/releases/download/$ver/moegirl.dict.yaml"

[rime-zhwiki]
src.webpage = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/expanded_assets/0.2.4"
src.regex = "zhwiki-([0-9]{8})\\.dict\\.yaml"
fetch.url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.4/zhwiki-$ver.dict.yaml"

[route-chain]
src.git = "https://github.com/xddxdd/route-chain.git"
fetch.github = "xddxdd/route-chain"

[sam-toki-mouse-cursors]
src.github = "SamToki/IconDesign---Sam-Toki-Mouse-Cursors"
fetch.github = "SamToki/IconDesign---Sam-Toki-Mouse-Cursors"

[sgx-software-enable]
src.git = "https://github.com/intel/sgx-software-enable.git"
fetch.github = "intel/sgx-software-enable"

[smartrent_py]
# src.pypi = "smartrent.py"
src.manual = "0.4.0"
fetch.pypi = "smartrent.py"

[soggy]
src.git = "https://github.com/LDAsuku/soggy.git"
fetch.github = "LDAsuku/soggy"

[stream-echo-nginx-module]
src.git = "https://github.com/openresty/stream-echo-nginx-module.git"
fetch.github = "openresty/stream-echo-nginx-module"

[th-tshyn]
src.webpage = "http://cheonhyeong.com/Simplified/download.html"
src.regex = "File/TH-Tshyn-([0-9.]+).7z"
fetch.url = "http://cheonhyeong.com/File/TH-Tshyn-$ver.7z"

[th-hak]
src.webpage = "http://cheonhyeong.com/Simplified/download.html"
src.regex = "File/TH-Hak-([0-9.]+).7z"
fetch.url = "http://cheonhyeong.com/File/TH-Hak-$ver.7z"

[th-joeng]
src.webpage = "http://cheonhyeong.com/Simplified/download.html"
src.regex = "File/TH-Joeng-([0-9.]+).7z"
fetch.url = "http://cheonhyeong.com/File/TH-Joeng-$ver.7z"

[th-khaai-t]
src.webpage = "http://cheonhyeong.com/Simplified/download.html"
src.regex = "File/TH-Khaai-T([0-9.]+).7z"
fetch.url = "http://cheonhyeong.com/File/TH-Khaai-T$ver.7z"

[th-khaai-p]
src.webpage = "http://cheonhyeong.com/Simplified/download.html"
src.regex = "File/TH-Khaai-P([0-9.]+).7z"
fetch.url = "http://cheonhyeong.com/File/TH-Khaai-P$ver.7z"

[th-ming]
src.webpage = "http://cheonhyeong.com/Simplified/download.html"
src.regex = "File/TH-Ming-([0-9.]+).7z"
fetch.url = "http://cheonhyeong.com/File/TH-Ming-$ver.7z"

[th-sung-t]
src.webpage = "http://cheonhyeong.com/Simplified/download.html"
src.regex = "File/TH-Sung-T([0-9.]+).7z"
fetch.url = "http://cheonhyeong.com/File/TH-Sung-T$ver.7z"

[th-sung-p]
src.webpage = "http://cheonhyeong.com/Simplified/download.html"
src.regex = "File/TH-Sung-P([0-9.]+).7z"
fetch.url = "http://cheonhyeong.com/File/TH-Sung-P$ver.7z"

[th-sy]
src.webpage = "http://cheonhyeong.com/Simplified/download.html"
src.regex = "File/TH-Sy-([0-9.]+).7z"
fetch.url = "http://cheonhyeong.com/File/TH-Sy-$ver.7z"

[transmission-web-control]
src.git = "https://github.com/ronggang/transmission-web-control.git"
fetch.github = "ronggang/transmission-web-control"

[uesave]
src.github = "trumank/uesave-rs"
fetch.github = "trumank/uesave-rs"

[uksmd]
src.github_tag = "CachyOS/uksmd"
fetch.github = "CachyOS/uksmd"

[undetected-chromedriver]
src.git = "https://github.com/ultrafunkamsterdam/undetected-chromedriver.git"
fetch.github = "ultrafunkamsterdam/undetected-chromedriver"

[vpp]
src.github_tag = "FDio/vpp"
src.include_regex = "^v[0-9.]+$"
fetch.github = "FDio/vpp"

[vs-rife]
src.github = "HolyWu/vs-rife"
fetch.github = "HolyWu/vs-rife"

[wechat-uos]
src.webpage = "https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=wechat-uos-bwrap"
src.regex = "\"Version\":\"([^\"]+)\""
src.from_pattern = "(.+)-(.+)"
src.to_pattern = "\\1"
fetch.url = "https://home-store-packages.uniontech.com/appstore/pool/appstore/c/com.tencent.wechat/com.tencent.wechat_$ver_amd64.deb"

[win2xcur]
src.github = "quantum5/win2xcur"
fetch.github = "quantum5/win2xcur"

[wine-wechat-x86]
src.github = "tom-snow/wechat-windows-versions-x86"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/tom-snow/wechat-windows-versions-x86/releases/download/v$ver/WeChatSetupX86-$ver.exe"

[wine-wechat-x64]
src.github = "tom-snow/wechat-windows-versions"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/tom-snow/wechat-windows-versions/releases/download/v$ver/WeChatSetup-$ver.exe"

[xstatic-asciinema-player]
src.pypi = "XStatic-asciinema-player"
fetch.pypi = "XStatic-asciinema-player"

[xstatic-font-awesome]
# src.pypi = "XStatic-Font-Awesome"
src.manual = "4.7.0.0"
fetch.pypi = "XStatic-Font-Awesome"

[zstd-nginx-module]
src.git = "https://github.com/tokers/zstd-nginx-module.git"
fetch.github = "tokers/zstd-nginx-module"
