[an-anime-game-launcher-bin]
src.github = "an-anime-team/an-anime-game-launcher"
fetch.url = "https://github.com/an-anime-team/an-anime-game-launcher/releases/download/$ver/an-anime-game-launcher-$ver.AppImage"

[an-anime-game-launcher-gtk-bin]
src.github = "an-anime-team/an-anime-game-launcher-gtk"
fetch.url = "https://github.com/an-anime-team/an-anime-game-launcher-gtk/releases/download/$ver/anime-game-launcher"

[asterisk-alaw16]
src.git = "https://github.com/traud/asterisk-alaw16.git"
fetch.github = "traud/asterisk-alaw16"

[asterisk-amr]
src.git = "https://github.com/traud/asterisk-amr.git"
fetch.github = "traud/asterisk-amr"

[asterisk-evs]
src.git = "https://github.com/traud/asterisk-evs.git"
fetch.github = "traud/asterisk-evs"

[asterisk-g72x]
src.git = "https://github.com/arkadijs/asterisk-g72x.git"
fetch.github = "arkadijs/asterisk-g72x"

[asterisk-gsm-efr]
src.git = "https://github.com/traud/asterisk-gsm-efr.git"
fetch.github = "traud/asterisk-gsm-efr"

[baidupcs-go]
src.github = "qjfoidnh/BaiduPCS-Go"
fetch.github = "qjfoidnh/BaiduPCS-Go"

[bilibili]
src.github_tag = "msojocs/bilibili-linux"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/msojocs/bilibili-linux/releases/download/v$ver/io.github.msojocs.bilibili_$ver_amd64.deb"

[bird-babel-rtt]
src.git = "https://github.com/NickCao/bird.git"
fetch.github = "NickCao/bird"

[bird-lg-go]
src.git = "https://github.com/xddxdd/bird-lg-go.git"
fetch.github = "xddxdd/bird-lg-go"

[boringssl-oqs]
src.github = "open-quantum-safe/boringssl"
fetch.github = "open-quantum-safe/boringssl"

[calibre-cops]
src.github = "seblucas/cops"
fetch.url = "https://github.com/seblucas/cops/releases/download/$ver/cops-$ver.zip"

[chromium-oqs-bin]
src.github = "open-quantum-safe/oqs-demos"
fetch.url = "https://github.com/open-quantum-safe/oqs-demos/releases/download/$ver/chromium-ubuntu-$ver.tgz"

[cloudpan189-go]
src.github = "tickstep/cloudpan189-go"
fetch.github = "tickstep/cloudpan189-go"

[coredns-lantian]
src.git = "https://github.com/xddxdd/coredns.git"
fetch.github = "xddxdd/coredns"

[dingtalk]
src.aur = "dingtalk-bin"
fetch.url = "https://dtapp-pub.dingtalk.com/dingtalk-desktop/xc_dingtalk_update/linux_deb/Release/com.alibabainc.dingtalk_$ver_amd64.deb"

[douban-openapi-server]
src.git = "https://github.com/caryyu/douban-openapi-server.git"
fetch.github = "caryyu/douban-openapi-server"

[drone-vault]
src.github_tag = "drone/drone-vault"
fetch.github = "drone/drone-vault"

[etherguard]
src.git = "https://github.com/KusakabeShi/EtherGuard-VPN.git"
fetch.github = "KusakabeShi/EtherGuard-VPN"

[fcitx5-breeze]
src.github = "scratch-er/fcitx5-breeze"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/scratch-er/fcitx5-breeze/releases/download/v$ver/fcitx5-breeze-prebuilt-$ver.tar.gz"

[flaresolverr]
src.github = "FlareSolverr/FlareSolverr"
fetch.github = "FlareSolverr/FlareSolverr"

[flasgger]
src.github = "flasgger/flasgger"
fetch.github = "flasgger/flasgger"

[genshin-checkin-helper]
src.git = "https://gitlab.com/y1ndan/genshin-checkin-helper.git"
fetch.git = "https://gitlab.com/y1ndan/genshin-checkin-helper.git"

[genshinhelper2]
src.git = "https://github.com/y1ndan/genshinhelper2.git"
fetch.github = "y1ndan/genshinhelper2"

[glauth]
src.github = "glauth/glauth"
fetch.github = "glauth/glauth"

[hoyo-glyphs]
src.git = "https://github.com/SpeedyOrc-C/Hoyo-Glyphs.git"
fetch.github = "SpeedyOrc-C/Hoyo-Glyphs"

[konnect]
src.github_tag = "Kopano-dev/konnect"
fetch.github = "Kopano-dev/konnect"

[ldap-auth-proxy]
src.git = "https://github.com/pinepain/ldap-auth-proxy.git"
fetch.github = "pinepain/ldap-auth-proxy"

[libltnginx]
src.git = "https://github.com/xddxdd/libltnginx.git"
fetch.github = "xddxdd/libltnginx"

[liboqs]
src.github = "open-quantum-safe/liboqs"
fetch.github = "open-quantum-safe/liboqs"

[linux-xanmod]
src.github_tag = "xanmod/linux"
src.exclude_regex = "^6\\.1\\.(.*)"
fetch.github = "xanmod/linux"

[linux-xanmod-unstable]
src.github_tag = "xanmod/linux"
fetch.github = "xanmod/linux"

[nbfc-linux-lantian]
src.git = "https://github.com/xddxdd/nbfc-linux.git"
fetch.github = "xddxdd/nbfc-linux"

[netboot-xyz-efi]
src.github = "netbootxyz/netboot.xyz"
fetch.url = "https://github.com/netbootxyz/netboot.xyz/releases/download/$ver/netboot.xyz.efi"

[netboot-xyz-lkrn]
src.github = "netbootxyz/netboot.xyz"
fetch.url = "https://github.com/netbootxyz/netboot.xyz/releases/download/$ver/netboot.xyz.lkrn"

[netns-exec]
src.git = "https://github.com/pekman/netns-exec.git"
fetch.github = "pekman/netns-exec"
git.fetchSubmodules = true

[nginx-module-stream-sts]
src.git = "https://github.com/vozlt/nginx-module-stream-sts.git"
fetch.github = "vozlt/nginx-module-stream-sts"

[nginx-module-sts]
src.git = "https://github.com/vozlt/nginx-module-sts.git"
fetch.github = "vozlt/nginx-module-sts"

[nginx-module-vts]
src.git = "https://github.com/vozlt/nginx-module-vts.git"
fetch.github = "vozlt/nginx-module-vts"

[nginx-njs]
src.github_tag = "nginx/njs"
fetch.github = "nginx/njs"

[ngx_brotli]
src.git = "https://github.com/google/ngx_brotli.git"
fetch.github = "google/ngx_brotli"

[noise-suppression-for-voice]
src.github = "werman/noise-suppression-for-voice"
fetch.github = "werman/noise-suppression-for-voice"

[nullfs]
src.git = "https://github.com/xrgtn/nullfs.git"
fetch.github = "xrgtn/nullfs"

[onepush]
src.git = "https://github.com/y1ndan/onepush.git"
fetch.github = "y1ndan/onepush"

[openssl-oqs]
src.git = "https://github.com/open-quantum-safe/openssl.git"
src.branch = "OQS-OpenSSL_1_1_1-stable"
fetch.github = "open-quantum-safe/openssl"

[openssl-oqs-provider]
src.git = "https://github.com/open-quantum-safe/oqs-provider.git"
fetch.github = "open-quantum-safe/oqs-provider"

[osdlyrics]
src.github = "osdlyrics/osdlyrics"
fetch.github = "osdlyrics/osdlyrics"

[payload-dumper-go]
src.github = "ssut/payload-dumper-go"
fetch.github = "ssut/payload-dumper-go"

[phpmyadmin]
src.github_tag = "phpmyadmin/phpmyadmin"
src.include_regex = "RELEASE_([0-9_]*)"
src.from_pattern = "RELEASE_([0-9])_([0-9])_([0-9])"
src.to_pattern = "\\1.\\2.\\3"
fetch.url = "https://files.phpmyadmin.net/phpMyAdmin/$ver/phpMyAdmin-$ver-all-languages.tar.xz"

[phppgadmin]
src.github = "ReimuHakurei/phppgadmin"
fetch.github = "ReimuHakurei/phppgadmin"

[plangothic-fonts]
src.github = "Fitzgerald-Porthmouth-Koenigsegg/Plangothic"
fetch.github = "Fitzgerald-Porthmouth-Koenigsegg/Plangothic"

[qbittorrent-enhanced-edition]
src.github = "c0re100/qBittorrent-Enhanced-Edition"
fetch.github = "c0re100/qBittorrent-Enhanced-Edition"

[qemu-user-static-amd64]
src.webpage = "https://sources.debian.org/api/src/qemu/"
src.regex = "\"version\":\"[0-9]+:([^\"]+)\""
fetch.url = "http://ftp.debian.org/debian/pool/main/q/qemu/qemu-user-static_$ver_amd64.deb"

[qemu-user-static-arm64]
src.webpage = "https://sources.debian.org/api/src/qemu/"
src.regex = "\"version\":\"[0-9]+:([^\"]+)\""
fetch.url = "http://ftp.debian.org/debian/pool/main/q/qemu/qemu-user-static_$ver_arm64.deb"

[qemu-user-static-armhf]
src.webpage = "https://sources.debian.org/api/src/qemu/"
src.regex = "\"version\":\"[0-9]+:([^\"]+)\""
fetch.url = "http://ftp.debian.org/debian/pool/main/q/qemu/qemu-user-static_$ver_armhf.deb"

[qemu-user-static-i386]
src.webpage = "https://sources.debian.org/api/src/qemu/"
src.regex = "\"version\":\"[0-9]+:([^\"]+)\""
fetch.url = "http://ftp.debian.org/debian/pool/main/q/qemu/qemu-user-static_$ver_i386.deb"

[qq-amd64]
src.webpage = "https://im.qq.com/rainbow/linuxQQDownload/"
src.regex = "\"https://dldir1.qq.com/qqfile/qq/QQNT/([^\"]+)_amd64.deb\""
fetch.url = "https://dldir1.qq.com/qqfile/qq/QQNT/$ver_amd64.deb"

[qq-arm64]
src.webpage = "https://im.qq.com/rainbow/linuxQQDownload/"
src.regex = "\"https://dldir1.qq.com/qqfile/qq/QQNT/([^\"]+)_arm64.deb\""
fetch.url = "https://dldir1.qq.com/qqfile/qq/QQNT/$ver_arm64.deb"

[qqmusic]
src.aur = "qqmusic-bin"
fetch.url = "https://dldir1.qq.com/music/clntupate/linux/deb/qqmusic_$ver_amd64.deb"

[rime-aurora-pinyin]
src.git = "https://github.com/hosxy/rime-aurora-pinyin.git"
fetch.github = "hosxy/rime-aurora-pinyin"

[rime-dict]
src.git = "https://github.com/Iorest/rime-dict.git"
fetch.github = "Iorest/rime-dict"

[rime-moegirl]
src.github = "outloudvi/mw2fcitx"
fetch.url = "https://github.com/outloudvi/mw2fcitx/releases/download/$ver/moegirl.dict.yaml"

[rime-zhwiki]
src.webpage = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases"
src.regex = "zhwiki-([0-9]{8})\\.dict\\.yaml"
fetch.url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.4/zhwiki-$ver.dict.yaml"

[route-chain]
src.git = "https://github.com/xddxdd/route-chain.git"
fetch.github = "xddxdd/route-chain"

[stream-echo-nginx-module]
src.git = "https://github.com/openresty/stream-echo-nginx-module.git"
fetch.github = "openresty/stream-echo-nginx-module"

[vs-rife]
src.github = "HolyWu/vs-rife"
fetch.github = "HolyWu/vs-rife"

[wechat-uos]
src.webpage = "https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=wechat-uos"
src.regex = "\"Version\":\"([^\"]+)\""
src.from_pattern = "(.+):(.+)-(.+)"
src.to_pattern = "\\2"
fetch.url = "https://home-store-packages.uniontech.com/appstore/pool/appstore/c/com.tencent.weixin/com.tencent.weixin_$ver_amd64.deb"

[zstd-nginx-module]
src.git = "https://github.com/tokers/zstd-nginx-module.git"
fetch.github = "tokers/zstd-nginx-module"
