[package]
name = "mediawiki"
version = "0.0.1"
authors = ["Peter Atashian <retep998@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
cookie = "0.15"
regex = "1.0"
reqwest = { version = "0.11", features = ["blocking", "multipart"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
debug = true