language: nix
nix: 2.2.2

sudo: false

env:
  global:
  - CACHIX_CACHE=bb010g
  - NUR_REPO=bb010g
  - BUILD_UNFREE=true

install:
- >
  mkdir -p "${XDG_CONFIG_DIR:-$HOME/.config}/nixpkgs" &&
  echo "{ allowUnfree = ${BUILD_UNFREE}; sandbox = true; }" > "${XDG_CONFIG_DIR:-$HOME/.config}/nixpkgs/config.nix"
- nix --version
- if [ -n "${CACHIX_CACHE}" ]; then travis_retry nix-channel --update; fi
- if [ -n "${CACHIX_CACHE}" ]; then nix-env -iA cachix -f https://cachix.org/api/v1/install; fi
- if [ -n "${CACHIX_CACHE}" ]; then cachix use "${CACHIX_CACHE}"; fi
- nix-channel --add "${NIX_CHANNEL}" nixpkgs
- travis_retry nix-channel --update

script:
- >
  while IFS= read -r drv; do
    nix-build "$drv" --show-trace | \
      if [ -n "${CACHIX_CACHE}" ]; then cachix push "${CACHIX_CACHE}"; fi
  done < <("$(nix-build ./default.nix -A nur-ci-helper)/bin/nur-ci-helper" \
    ./ci.nix -A cacheOutputs)
- nix-build ./ci.nix -A buildOutputs
- nix eval -f ./default.nix 'lib'
- nix eval -f ./default.nix 'modules'
- nix eval -f ./default.nix 'overlays'

jobs:
  include:
  - name: 'nixpkgs-unstable'
    env: NIX_CHANNEL=https://nixos.org/channels/nixpkgs-unstable
  - name: 'nixos-unstable (bb010g)'
    env: NIX_CHANNEL=https://github.com/bb010g/nixpkgs/archive/bb010g-nixos-unstable.tar.gz
  - name: 'nixos-unstable'
    env: NIX_CHANNEL=https://nixos.org/channels/nixos-unstable
  - name: 'nixos-19.03'
    env: NIX_CHANNEL=https://nixos.org/channels/nixos-19.03
  - stage: deploy
    name: "Notify NUR"
    if: 'type NOT IN (pull_request, cron) AND branch IN (master)'
    install:
    script:
    - curl -XPOST "https://nur-update.herokuapp.com/update?repo=${NUR_REPO}"

# vim:et:sw=2
