[webcrack]
src.github = "j4k0xb/webcrack"
fetch.github = "j4k0xb/webcrack"

[huawei-password-tool]
src.github = "0xuserpag3/HuaweiPasswordTool"
fetch.github = "0xuserpag3/HuaweiPasswordTool"

[thinkpad-uefi-sign]
src.git = "https://github.com/thrimbor/thinkpad-uefi-sign"
fetch.github = "thrimbor/thinkpad-uefi-sign"

[pa]
src.git = "https://github.com/biox/pa"
fetch.github = "biox/pa"

[sfp-master]
src.github_tag = "bigbigmdm/SFP-Master"
fetch.github = "bigbigmdm/SFP-Master"

[gerber2pdf]
src.github_tag = "jpt13653903/Gerber2PDF"
fetch.github = "jpt13653903/Gerber2PDF"
git.fetchSubmodules = true
