[ghostty]
src.github_tag = "ghostty-org/ghostty"
src.prefix = "v"
fetch.url = "https://release.files.ghostty.org/$ver/Ghostty.dmg"
[ghostty-nightly]
src.manual = "tip"
fetch.url = "https://github.com/ghostty-org/ghostty/releases/download/tip/ghostty-macos-universal.zip"
fetch.force = true
url.name = "Ghostty.zip"
extract = ["**/*"]
[zen]
src.github = "zen-browser/desktop"
fetch.url = "https://github.com/zen-browser/desktop/releases/download/$ver/zen.macos-universal.dmg"
[zen-twilight]
src.github = "zen-browser/desktop"
fetch.url = "https://github.com/zen-browser/desktop/releases/download/twilight/zen.macos-universal.dmg"
[bartender-6]
#src.manual = 'B2'
src.manual = "6-0-0"
fetch.url = "https://macbartender.com/B2/updates/$ver/Bartender%206.dmg"
url.name = "Bartender6.dmg"
[yabai]
src.github = "koekeishiya/yabai"
fetch.github = "koekeishiya/yabai"

[karabiner-dk]
src.github = "pqrs-org/Karabiner-DriverKit-VirtualHIDDevice"
fetch.github = "pqrs-org/Karabiner-DriverKit-VirtualHIDDevice"

[kanata]
src.github_tag = "jtroo/kanata"
src.sort_version_key = "awesomeversion"
fetch.github = "jtroo/kanata"
cargo_lock = ["Cargo.lock"]
[kanata-vk-agent]
src.git = "https://github.com/auscyber/kanata-vk-agent"
fetch.github = 'auscyber/kanata-vk-agent'

[helium-macos]
src.github_tag = "imputnet/helium-macos"
fetch.url = "https://github.com/imputnet/helium-macos/releases/download/$ver/helium_$ver_arm64-macos.dmg"
[helium-linux]
src.github_tag = "imputnet/helium-linux"
fetch.github = "imputnet/helium-linux"
[flake-compat]
src.manual = "flake-compat"
fetch.tarball = "https://git.lix.systems/lix-project/flake-compat/archive/main.tar.gz"
tarball.name = "flake-compat.tar.gz"
extract = ["default.nix"]

