[ghostty]
src.github_tag = "ghostty-org/ghostty"
src.prefix = "v"
fetch.url = "https://release.files.ghostty.org/$ver/Ghostty.dmg"
[ghostty-nightly]
src.manual = "tip"
fetch.url = "https://github.com/ghostty-org/ghostty/releases/download/tip/Ghostty.dmg"
fetch.force = true
[zen-browser]
src.github = "zen-browser/desktop"
fetch.url = "https://github.com/zen-browser/desktop/releases/download/$ver/zen.macos-universal.dmg"
[zen-browser-twilight]
src.github = "zen-browser/desktop"
fetch.url = "https://github.com/zen-browser/desktop/releases/download/twilight/zen.macos-universal.dmg"
[bartender-alpha]
#src.webpage = "https://macbartender.com/Bartender6/alpha.html"
#src.regex = 'Bartender 6 Beta (\w+)'
src.manual = 'B2'
fetch.url = "https://macbartender.com/updates/b6/Bartender6-$ver.zip"
url.name = "Bartender6-$ver.zip"

