name: Update Sources

on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: update-sources
  cancel-in-progress: true

jobs:
  update-sources:
    runs-on: ubuntu-latest
    name: Update Sources
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: wimpysworld/nothing-but-nix@v6
        with:
          hatchet-protocol: "rampage"

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true

      - name: Restore and save Nix store
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Update sources
        run: |
          nix flake update
          nix run .#nvfetcher
          nix fmt _sources
          pkgs/pixes/update.sh
          pkgs/pixes/update-git.sh
          pkgs/splayer-git/update-git.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          commit-message: Update sources
          branch: ci/update-sources
          delete-branch: true
          title: Update sources
          labels: dependencies
