name: Update Sources

on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: update-sources
  cancel-in-progress: true

jobs:
  update-sources:
    runs-on: ubuntu-latest
    name: Update Sources
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            accept-flake-config = true

      - name: Update sources
        run: |
          nix flake update
          nix run nixpkgs#nvfetcher
          nix fmt _sources
          pkgs/pixes/update.sh
          pkgs/pixes/update-git.sh
          pkgs/splayer-git/update-git.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          commit-message: Update sources
          branch: ci/update-sources
          delete-branch: true
          title: Update sources
          labels: dependencies
