[algermusicplayer-arm]
fetch.url = "https://github.com/algerkong/AlgerMusicPlayer/releases/download/v$ver/AlgerMusicPlayer-$ver-linux-arm64.AppImage"
src.github = "algerkong/AlgerMusicPlayer"
src.prefix = "v"

[algermusicplayer-x86]
fetch.url = "https://github.com/algerkong/AlgerMusicPlayer/releases/download/v$ver/AlgerMusicPlayer-$ver-linux-x86_64.AppImage"
src.github = "algerkong/AlgerMusicPlayer"
src.prefix = "v"

[ayugram-desktop]
fetch.github = "AyuGram/AyuGramDesktop"
git.fetchSubmodules = true
src.github = "AyuGram/AyuGramDesktop"

[danmakufactory]
fetch.github = "hihkm/DanmakuFactory"
src.github = "hihkm/DanmakuFactory"

[danmakufactory-git]
fetch.github = "hihkm/DanmakuFactory"
git.fetchSubmodules = true
src.git = "https://github.com/hihkm/DanmakuFactory"

[dxvk-gplall]
fetch.url = "https://github.com/Digger1955/dxvk-gplasync-lowlatency/releases/download/DXVK-GPLALL-$ver/DXVK-GPLALL-MSVC-Windows-AVX2-O2-LTCG-AMD64.$ver.zip"
src.github = "Digger1955/dxvk-gplasync-lowlatency"
src.prefix = "DXVK-GPLALL-"

[imfile-arm]
fetch.url = "https://github.com/imfile-io/imfile-desktop/releases/download/v$ver/imFile-$ver-arm64.AppImage"
src.github = "imfile-io/imfile-desktop"
src.prefix = "v"

[imfile-x86]
fetch.url = "https://github.com/imfile-io/imfile-desktop/releases/download/v$ver/imFile-$ver.AppImage"
src.github = "imfile-io/imfile-desktop"
src.prefix = "v"

[jaq]
cargo_locks = ["Cargo.lock"]
fetch.github = "01mf02/jaq"
src.github_tag = "01mf02/jaq"

[lxgw-wenkai-gb]
fetch.url = "https://github.com/lxgw/LxgwWenkaiGB/releases/download/$ver/lxgw-wenkai-gb-$ver.tar.gz"
src.github = "lxgw/LxgwWenkaiGB"

[piliplus]
extract = ["pubspec.lock"]
fetch.github = "bggRGjQaUbCoE/PiliPlus"
src.github = "bggRGjQaUbCoE/PiliPlus"

[pixes]
extract = ["pubspec.lock"]
fetch.github = "wgh136/pixes"
src.github = "wgh136/pixes"

[pixes-git]
extract = ["pubspec.lock"]
fetch.github = "wgh136/pixes"
src.git = "https://github.com/wgh136/pixes"

[splayer-git]
fetch.github = "imsyy/SPlayer"
src.git = "https://github.com/imsyy/SPlayer"

[uosc-danmaku]
fetch.github = "Tony15246/uosc_danmaku"
src.github = "Tony15246/uosc_danmaku"

[uosc-danmaku-git]
fetch.github = "Tony15246/uosc_danmaku"
src.git = "https://github.com/Tony15246/uosc_danmaku"

[zhuque]
fetch.url = "https://github.com/TrionesType/zhuque/releases/download/$ver/ZhuqueFangsong-$ver.zip"
src.github_tag = "TrionesType/zhuque"
