[material-fox]
src.github_tag = "muckSponge/MaterialFox"
fetch.github = "muckSponge/MaterialFox"

[arkenfox-userjs]
src.github_tag = "arkenfox/user.js"
fetch.github = "arkenfox/user.js"

[clash-speedtest]
src.github_tag = "starudream/clash-speedtest"
fetch.github = "starudream/clash-speedtest"

## VS Code Extensions

['vscode-extensions.mads-hartmann.bash-ide-vscode']
src.vsmarketplace = "mads-hartmann.bash-ide-vscode"
fetch.vsmarketplace = "mads-hartmann.bash-ide-vscode"
passthru = { license = "mit", homepage = "https://github.com/bash-lsp/bash-language-server", description = "Bash language server implementation based on Tree Sitter and its grammar for Bash with explainshell integration." }

['vscode-extensions.shardulm94.trailing-spaces']
src.vsmarketplace = "shardulm94.trailing-spaces"
fetch.vsmarketplace = "shardulm94.trailing-spaces"
passthru = { license = "mit", homepage = "https://github.com/shardulm94/vscode-trailingspaces", description = "highlight trailing spaces and delete them in a flash." }

['vscode-extensions.ccls-project.ccls']
src.vsmarketplace = "ccls-project.ccls"
fetch.vsmarketplace = "ccls-project.ccls"
passthru = { license = "free", homepage = "https://github.com/MaskRay/vscode-ccls", description = "ccls plugin for Visual Studio Code." }

['vscode-extensions.TabNine.tabnine-vscode']
src.vsmarketplace = "TabNine.tabnine-vscode"
fetch.vsmarketplace = "TabNine.tabnine-vscode"
passthru = { license = "mit", homepage = "https://github.com/codota/tabnine-vscode", description = "Tabnine is the AI code completion tool trusted by millions of developers to code faster with fewer errors." }

['vscode-extensions.vscode-icons-team.vscode-icons']
src.vsmarketplace = "vscode-icons-team.vscode-icons"
fetch.vsmarketplace = "vscode-icons-team.vscode-icons"
passthru = { license = "mit", homepage = "https://github.com/vscode-icons/vscode-icons", description = "Icons for Visual Studio Code." }

['vscode-extensions.timonwong.shellcheck']
src.vsmarketplace = "timonwong.shellcheck"
fetch.vsmarketplace = "timonwong.shellcheck"
passthru = { license = "mit", homepage = "https://github.com/vscode-shellcheck/vscode-shellcheck", description = "Integrates ShellCheck into VS Code, a linter for Shell scripts." }

['vscode-extensions.twxs.cmake']
src.vsmarketplace = "twxs.cmake"
fetch.vsmarketplace = "twxs.cmake"
passthru = { license = "mit", homepage = "https://github.com/twxs/vs.language.cmake", description = "CMake langage support for Visual Studio Code."}

['vscode-extensions.LivingThings.p4']
src.vsmarketplace = "LivingThings.p4"
fetch.vsmarketplace = "LivingThings.p4"
passthru = { license = "free", homepage = "https://github.com/zznobodyzz/vscode-p4-extention", description = "p4-16 langage support for Visual Studio Code."}

['vscode-extensions.vmsynkov.colonize']
src.vsmarketplace = "vmsynkov.colonize"
fetch.vsmarketplace = "vmsynkov.colonize"
passthru = { license = "free", homepage = "https://github.com/vmsynkov-zz/colonize", description = "Adds three shotcuts to insert semicolons with ease"}

['vscode-extensions.GitHub.copilot']
src.vsmarketplace = "GitHub.copilot"
fetch.vsmarketplace = "GitHub.copilot"
passthru = { license = "cc-by-40", homepage = "https://marketplace.visualstudio.com/items?itemName=GitHub.copilot", description="GitHub Copilot is an AI pair programmer which suggests line completions and entire function bodies as you type. "}

['vscode-extensions.LeetCode.vscode-leetcode']
src.vsmarketplace = "LeetCode.vscode-leetcode"
fetch.vsmarketplace = "LeetCode.vscode-leetcode"
passthru = { license = "mit", homepage = "https://github.com/LeetCode-OpenSource/vscode-leetcode", description="Solve LeetCode problems in VS Code"}

