language: nix

env:
  global:
    - CACHIX_CACHE=metadark
    - NUR_REPO=metadark
    - NIXPKGS_ALLOW_UNFREE=1

jobs:
  fast_finish: true

  include:
    - stage: Build & Test
      name: "linux: nixpkgs-unstable"
      os: linux
      env: NIX_CHANNEL=https://nixos.org/channels/nixpkgs-unstable
      script: source travis/build.sh
    - os: linux
      name: "linux: nixos-unstable"
      env: NIX_CHANNEL=https://nixos.org/channels/nixos-unstable
      script: source travis/build.sh
    - os: linux
      name: "linux: nixos-19.09"
      env: NIX_CHANNEL=https://nixos.org/channels/nixos-19.09
      script: source travis/build.sh
    - os: osx
      name: "macOS: nixpkgs-unstable"
      env: NIX_CHANNEL=https://nixos.org/channels/nixpkgs-unstable
      script: source travis/build.sh
    - os: osx
      name: "macOS: nixpkgs-19.09-darwin"
      env: NIX_CHANNEL=https://nixos.org/channels/nixpkgs-19.09-darwin
      script: source travis/build.sh

    - stage: Deploy
      script: source travis/deploy.sh
      if: type IN (push, api) AND branch = master

  allow_failures:
    - os: osx
      env: NIX_CHANNEL=https://nixos.org/channels/nixpkgs-unstable
      script: source travis/build.sh
    - os: osx
      env: NIX_CHANNEL=https://nixos.org/channels/nixpkgs-19.09-darwin
      script: source travis/build.sh

install: source travis/setup.sh
