name: auto-update
on:
  workflow_dispatch:
  schedule:
    # Nominally 05:11 GMT+3, but actual start times apparently suffer from delays
    - cron: '11 2 * * *'

defaults:
  run:
    shell: bash

env:
  CACHIX_NAME: sigprof

  nur_channels: nixpkgs-unstable nixos-unstable nixos-22.05 nixos-21.11

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        item:
          - pkgs/mozilla-langpack

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Install Nix
        uses: cachix/install-nix-action@daddc62a2e67d1decb56e028c9fa68344b9b7c2a
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Cachix
        uses: cachix/cachix-action@v11
        with:
          name: ${{ env.CACHIX_NAME }}
          extraPullNames: "pre-commit-hooks"

      - name: Run the update script
        env:
          item: ${{ matrix.item }}
        run: |
          # Run the update script
          case "$item" in
            pkgs/mozilla-langpack)
              set -- @flake
              for channel in $nur_channels; do
                set -- "$@" "@$channel"
              done
              "$item"/update.sh "$@"
              ;;
            *)
              "$item"/update.sh
              ;;
          esac

      - name: Generate a GitHub token
        id: token
        uses: tibdex/github-app-token@v1.7.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create a PR
        id: pr
        uses: peter-evans/create-pull-request@v4.2.0
        with:
          token: ${{ steps.token.outputs.token }}
          commit-message: "chore(${{ matrix.item }}): Automatic update"
          author: "sigprof[bot] <108069352+sigprof[bot]@users.noreply.github.com>"
          branch: "auto-update/${{ matrix.item }}"
          delete-branch: true
          title: "chore(${{ matrix.item }}): Automatic update"
          body: |
            Automatic update of `${{ matrix.item }}`.

            Generated by the [GitHub workflow run](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}).
          labels: "autorebase:opt-in"

      - name: Enable automerge for the PR
        if: >
          steps.pr.outputs.pull-request-operation == 'created'
          && (
            (matrix.item == 'pkgs/mozilla-langpack')
          )
        uses: peter-evans/enable-pull-request-automerge@v2.2.1
        with:
          token: ${{ steps.token.outputs.token }}
          pull-request-number: ${{ steps.pr.outputs.pull-request-number }}
          merge-method: squash
