[seamonkey]
src.webpage = "https://www.seamonkey-project.org/releases/"
src.regex = "SeaMonkey ([0-9\\.]+) [^B]"
fetch.tarball = "https://archive.seamonkey-project.org/releases/$ver/linux-x86_64/en-US/seamonkey-$ver.en-US.linux-x86_64.tar.bz2"

[trufflesqueak]
src.github = "hpi-swa/trufflesqueak"
fetch.url = "https://github.com/hpi-swa/trufflesqueak/releases/download/$ver/trufflesqueak-$ver-linux-amd64.tar.gz"

[trufflesqueak-image]
src.github = "hpi-swa/trufflesqueak"
fetch.url = "https://github.com/hpi-swa/trufflesqueak/releases/download/$ver/TruffleSqueakImage-24.0.0.zip"

[guile-config]
src.manual = "0.5.0"
fetch.tarball = "https://gitlab.com/a-sassmannshausen/guile-config/-/archive/$ver/guile-config-$ver.tar.gz"

[guile-hall]
src.manual = "0.4.1"
fetch.tarball = "https://gitlab.com/a-sassmannshausen/guile-hall/-/archive/$ver/guile-hall-$ver.tar.gz"

[cakeml]
src.github_tag = "cakeml/cakeml"
fetch.tarball = "https://github.com/CakeML/cakeml/releases/download/$ver/cake-x64-64.tar.gz"

[enso]
src.github = "enso-org/enso"
fetch.url = "https://github.com/enso-org/enso/releases/download/$ver/enso-linux-x86_64-$ver.AppImage"

[wasmfxtime]
src.git = "https://github.com/wasmfx/wasmfxtime"
fetch.github = "wasmfx/wasmfxtime"
cargo_locks = ["./Cargo.lock"]
git.fetchSubmodules = true
