[HelveticaNeueCyr]
fetch.github = "Vortriz/fonts"
git.sparseCheckout = ["HelveticaNeueCyr.tar.gz"]
src.git = "https://github.com/Vortriz/fonts"

[SFMono-Nerd-Font-Ligaturized]
fetch.github = "shaunsingh/SFMono-Nerd-Font-Ligaturized"
src.git = "https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized"

[dunefetch]
fetch.github = "datavorous/dunefetch"
src.git = "https://github.com/datavorous/dunefetch"

[goldfish]
cargo_locks = ["Cargo.lock"]
fetch.github = "sameoldlab/goldfish"
src.git = "https://github.com/sameoldlab/goldfish"

[libfprint-focaltech-2808-a658-alt]
fetch.url = "https://github.com/Varrkan82/RTS5811-FT9366-fingerprint-linux-driver-with-VID-2808-and-PID-a658/raw/b040ccd953c27e26c1285c456b4264e70b36bc3f/libfprint-2-2-$ver+tod1-FT9366_20240627.x86_64.rpm"
src.manual = "1.94.4"

[xdg-desktop-portal-termfilechooser]
fetch.github = "hunkyburrito/xdg-desktop-portal-termfilechooser"
src.git = "https://github.com/hunkyburrito/xdg-desktop-portal-termfilechooser"
