[HelveticaNeueCyr]
fetch.github = "Vortriz/fonts"
git.sparseCheckout = ["HelveticaNeueCyr.tar.gz"]
src.git = "https://github.com/Vortriz/fonts"

[SFMono-Nerd-Font-Ligaturized]
fetch.github = "shaunsingh/SFMono-Nerd-Font-Ligaturized"
src.git = "https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized"

[dunefetch]
fetch.github = "datavorous/dunefetch"
src.git = "https://github.com/datavorous/dunefetch"

[goldfish]
cargo_locks = ["Cargo.lock"]
fetch.github = "sameoldlab/goldfish"
src.git = "https://github.com/sameoldlab/goldfish"

[xdg-desktop-portal-termfilechooser]
fetch.github = "hunkyburrito/xdg-desktop-portal-termfilechooser"
src.git = "https://github.com/hunkyburrito/xdg-desktop-portal-termfilechooser"
