prefix = "fdcc::"

[node.hastur]
# homeserver censored
id = 0                                                                                       # ro, for Cantor Pair Function
censor = true
nat = true
region = 0
user = "riro"
ssh_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM4XC7dGxwY7VUPr4t+NtWL+c7pTl8g568jdv6aRbhDZ"
link_local_addr = "fe80::216:3eff:fe0f:37d8/64"
wg_key = "BCbrvvMIoHATydMkZtF8c+CHlCpKUy1NW+aP0GnYfRM="
# identifiers = [{ name = "hastur.local", type = "mdns" }]
addrs = ["192.168.1.2"]

[node.kaambl]
# laptop
id = 1
censor = true
nat = true
region = 0
user = "elen"
ssh_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKQ8LFIGiv5IEqra7/ky0b0UgWdTGPY1CPA9cH8rMnyf"
link_local_addr = "fe80::216:3eff:fe66:f780/64"
wg_key = "i7Li/BDu5g5+Buy6m6Jnr09Ne7xGI/CcNAbyK9KKbQg="
addrs = ["192.168.1.186"]
# identifiers = [{ name = "kaambl.local", type = "mdns" }]

[node.eihort]
# nas
id = 2
censor = true
nat = true
region = 0
user = "elen"
ssh_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIImlt3ABsoFfuPwiPR2vyO8sDAFEQtu3BKPqrCBdcsch"
link_local_addr = "fe80::216:3eff:fe4f:e85f/64"
wg_key = "69DTVyNbhMN6/cgLCpcZrh/kGoi1IyxV0QwVjDe5IQk="

addrs = ["192.168.1.110"]
# identifiers = [{ name = "eihort.local", type = "mdns" }]


[node.yidhra]
id = 3
addrs = ["205.198.76.6", "2404:c140:2000:2::32:1d9f"]
censor = false
nat = false
user = "elen"
ssh_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJfA9a0Uetc/vt0rHTulnQNHZPqJNy9ZyLvmP5GDnaoc"
link_local_addr = "fe80::216:3eff:fe41:49c6/64"
wg_key = "V3J9d8lUOk4WXj+dIiAZsuKJv3HxUl8J4HvX/s4eElY="
iata = "NRT"

[node.abhoth]
# dmit
id = 4
addrs = ["154.31.114.112", "2403:18c0:1000:13a:343b:65ff:fe1b:7a0f"]
censor = false
nat = false
user = "elen"
ssh_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFRMxm3SFj1DwUjCTF4ByMVYQNMOPzi/Kqff5fTEvtG9"
link_local_addr = "fe80::216:3eff:fe15:ec52/64"
wg_key = "jQGcU+BULglJ9pUz/MmgOWhGRjpimogvEudwc8hMR0A="
iata = "NRT"

# [node.azasos]
# # tencent cloud | censored
# id = 5
# addr = "116.196.112.43"
# censor = true
# nat = false
# user = "elen"

# unique_addr = "fdcc::6/128"
# link_local_addr = "fe80::216:3eff:fe6c:5a57/64"
# pub_key = "49xNnrpNKHAvYCDikO3XhiK94sUaSQ4leoCnTOQjWno="
