[material-fox]
src.github_tag = "muckSponge/MaterialFox"
fetch.github = "muckSponge/MaterialFox"

[arkenfox-userjs]
src.github_tag = "arkenfox/user.js"
fetch.github = "arkenfox/user.js"

[clash-speedtest]
src.github_tag = "starudream/clash-speedtest"
fetch.github = "starudream/clash-speedtest"
pinned = true

[clash-geoip]
src.github_tag = "Dreamacro/maxmind-geoip"
fetch.url = "https://github.com/Dreamacro/maxmind-geoip/releases/download/$ver/Country.mmdb"

[yacd]
src.github_tag = "haishanh/yacd"
fetch.tarball = "https://github.com/haishanh/yacd/releases/download/$ver/yacd.tar.xz"

## VS Code Extensions

[remote-containers]
src.vsmarketplace = "ms-vscode-remote.remote-containers"
fetch.vsmarketplace = "ms-vscode-remote.remote-containers"
pinned = true

[remote-containers.passthru]
license = "free"
homepage = "https://github.com/Microsoft/vscode-remote-release"
description="Open any folder or repository inside a Docker container."
collection = "vscode-extensions"
publisher = "ms-vscode-remote"
