name: "Build and populate cache"
on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron:  '11 */4 * * *'
  workflow_dispatch:
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-15
        nixPath:
          - nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/master.tar.gz
          - nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/nixpkgs-unstable.tar.gz
          - nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/nixos-unstable.tar.gz
          - nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/nixos-unstable-small.tar.gz
          - nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/staging-next.tar.gz
          - nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/release-25.11.tar.gz
        # Set this to notify the global nur package registry that changes are
        # available.
        #
        # The repo name as used in
        # https://github.com/nix-community/NUR/blob/master/repos.json
        nurRepo:
          - mio
        # Set this to cache your build results in cachix for faster builds
        # in CI and for everyone who uses your cache.
        #
        # Format: Your cachix cache host name without the ".cachix.org" suffix.
        # Example: mycache (for mycache.cachix.org)
        #
        # For this to work, you also need to set the CACHIX_SIGNING_KEY or
        # CACHIX_AUTH_TOKEN secret in your repository secrets settings in
        # Github found at
        # https://github.com/<your_githubname>/nur-packages/settings/secrets
        cachixName:
          - mio
    runs-on: "${{ matrix.os }}"
    steps:
    - name: Maximize build space
      if: runner.os == 'Linux'
      uses: mio-19/maximize-build-space@patch-1
      with:
        root-reserve-mb: 512
        swap-size-mb: 40000
        overprovision-lvm: 'true'
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
        build-mount-path: /nix
    - name: Checkout repository
      uses: actions/checkout@v6
    - name: Install nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: "${{ matrix.nixPath }}"
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= mio.cachix.org-1:FlupyyLPURqwdRqtPT/LBWKsXY7JKsDkzZQo2K6LeMM= mio-cache.cachix.org-1:ouuIJZ59HIflYjpLW6DRyMc1c+6r3kC/LHuqGUsWigg= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= chaotic-nyx.cachix.org-1:HfnXSw4pj95iI/n17rIDy40agHj12WfF+Gqk6SonIT8= staging.cachix.org-1:WX63nyFdVdWGn6n59pIYwkcH/AtjJGjvMQFKlI2z00w=
          substituters = https://mio.cachix.org/ https://mio-cache.cachix.org/ https://cache.garnix.io https://nix-community.cachix.org/ https://chaotic-nyx.cachix.org/ https://cache.nixos.org/ https://staging.cachix.org/
    - name: Show nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    - name: Setup cachix
      uses: cachix/cachix-action@v16
      # Don't replace <YOUR_CACHIX_NAME> here!
      if: ${{ matrix.cachixName != '<YOUR_CACHIX_NAME>' }}
      with:
        name: ${{ matrix.cachixName }}
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Determine system architecture
      run: |
        if [[ "${{ runner.os }}" == "macOS" ]]; then
          if [[ "${{ runner.arch }}" == "ARM64" ]]; then
            SYSTEM="aarch64-darwin"
          else
            SYSTEM="x86_64-darwin"
          fi
        elif [[ "${{ runner.arch }}" == "ARM64" ]]; then
          SYSTEM="aarch64-linux"
        else
          SYSTEM="x86_64-linux"
        fi
        echo "SYSTEM=$SYSTEM" >> $GITHUB_ENV
        echo "Building for system: $SYSTEM"
    # https://github.com/nix-community/nixos-apple-silicon/blob/7aad69158fc1b5bbbddac19040b6aae14daaa35c/.github/workflows/cache.yml#L45C56-L50C24
    - name: Build nix packages
      run: |
        nice -n 20 nix run nixpkgs#nix-fast-build -- --max-jobs 1 --option cores 1 --option max-jobs 1 \
          --no-nom --skip-cached \
          -f .#packages.${{ env.SYSTEM }} ${{ matrix.nixpkgs-override }}
    - name: Trigger NUR update
      # Don't replace <YOUR_REPO_NAME> here!
      if: ${{ matrix.nurRepo != '<YOUR_REPO_NAME>' }}
      run: curl -XPOST "https://nur-update.nix-community.org/update?repo=${{ matrix.nurRepo }}"
