name: "Auto-update packages"
on:
  schedule:
    # Run every day at 03:00 UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Install nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/nixpkgs-unstable.tar.gz
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Configure git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Update lmms
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd pkgs/lmms
        ./update.sh

    - name: Update musescore3
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd pkgs/musescore3
        ./update.sh

    - name: Update firefox nightly
      continue-on-error: true
      run: nix run .#firefox_nightly-unwrapped.passthru.updateScript

    - name: Update nss-git
      continue-on-error: true
      run: nix run .#nss_git.passthru.updateScript

    - name: Update proton-cachyos
      continue-on-error: true
      run: nix run .#proton-cachyos.passthru.updateScript

    - name: Update proton-cachyos x86_64_v2
      continue-on-error: true
      run: nix run .#proton-cachyos_x86_64_v2.passthru.updateScript

    - name: Update proton-cachyos x86_64_v3
      continue-on-error: true
      run: nix run .#proton-cachyos_x86_64_v3.passthru.updateScript

    - name: Update proton-cachyos x86_64_v4
      continue-on-error: true
      run: nix run .#proton-cachyos_x86_64_v4.passthru.updateScript

    - name: Update proton-ge-custom
      continue-on-error: true
      run: nix run .#proton-ge-custom.passthru.updateScript

    - name: Update plezy
      continue-on-error: true
      run: nix run .#plezy.passthru.updateScript

    - name: Push changes
      run: |
        git push
