# See https://www.git-town.com/configuration-file for details

[branches]
main = "main"
order = "asc"

[create]
new-branch-type = "feature"
share-new-branches = "no"
stash = true

[ship]
delete-tracking-branch = false
strategy = "api"

[sync]
auto-sync = true
feature-strategy = "merge"
perennial-strategy = "ff-only"
prototype-strategy = "merge"
push-branches = false
push-hook = true
tags = true
upstream = false
