[exloli-next]
src.git = "https://github.com/lolishinshi/exloli-next"
fetch.github = "lolishinshi/exloli-next"

[flapalerted]
src.git = "https://github.com/Kioubit/FlapAlerted"
fetch.github = "Kioubit/FlapAlerted"

[flapalerted-stable]
src.github = "Kioubit/FlapAlerted"
fetch.github = "Kioubit/FlapAlerted"

[pixy2]
src.git = "https://github.com/charmedlabs/pixy2"
fetch.github = "charmedlabs/pixy2"

[geolite2-asn]
src.github = "P3TERX/GeoLite.mmdb"
fetch.url = "https://github.com/P3TERX/GeoLite.mmdb/releases/download/$ver/GeoLite2-ASN.mmdb"

[geolite2-city]
src.github = "P3TERX/GeoLite.mmdb"
fetch.url = "https://github.com/P3TERX/GeoLite.mmdb/releases/download/$ver/GeoLite2-City.mmdb"

[geolite2-country]
src.github = "P3TERX/GeoLite.mmdb"
fetch.url = "https://github.com/P3TERX/GeoLite.mmdb/releases/download/$ver/GeoLite2-Country.mmdb"

[v2ray-rules-dat-geoip]
src.github = "Loyalsoldier/v2ray-rules-dat"
fetch.url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/download/$ver/geoip.dat"

[v2ray-rules-dat-geosite]
src.github = "Loyalsoldier/v2ray-rules-dat"
fetch.url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/download/$ver/geosite.dat"

[libinput-three-finger-drag]
src.git = "https://github.com/marsqing/libinput-three-finger-drag"
fetch.github = "marsqing/libinput-three-finger-drag"

[english_words]
src.git = "https://github.com/dwyl/english-words.git"
fetch.github = "dwyl/english-words"

[fcitx5-themes-candlelight]
src.git = "https://github.com/thep0y/fcitx5-themes-candlelight.git"
fetch.github = "thep0y/fcitx5-themes-candlelight"

[mm-geofeed-verifier]
src.github = "maxmind/mm-geofeed-verifier"
fetch.github = "maxmind/mm-geofeed-verifier"

[bark-server-stable]
src.github = "Finb/bark-server"
fetch.github = "Finb/bark-server"

[bark-server]
src.git = "https://github.com/Finb/bark-server.git"
fetch.github = "Finb/bark-server"

[watt-toolkit-x86_64-linux]
src.github = "BeyondDimension/SteamTools"
fetch.url = "https://github.com/BeyondDimension/SteamTools/releases/download/$ver/Steam++_v$ver_linux_x64.tgz"

[watt-toolkit-aarch64-linux]
src.github = "BeyondDimension/SteamTools"
fetch.url = "https://github.com/BeyondDimension/SteamTools/releases/download/$ver/Steam++_v$ver_linux_arm64.tgz"

# [gzctf-contributors]
# src.manual = "0.0.0"
# fetch.url = "https://api.github.com/repos/GZTimeWalker/GZCTF/contributors"
#
# [gzctf]
# src.github = "GZTimeWalker/GZCTF"
# fetch.github = "GZTimeWalker/GZCTF"

[mautrix-telegramgo]
src.git = "https://github.com/mautrix/telegramgo.git"
fetch.github = "mautrix/telegramgo"

[new-api]
src.github = "QuantumNous/new-api"
fetch.github = "QuantumNous/new-api"

[aliyundrive-webdav-stable]
src.github = "messense/aliyundrive-webdav"
fetch.github = "messense/aliyundrive-webdav"

[aliyundrive-webdav]
src.git = "https://github.com/messense/aliyundrive-webdav.git"
fetch.github = "messense/aliyundrive-webdav"

[mpv-danmaku]
src.github = "moraxyc/mpv-danmaku"
fetch.github = "moraxyc/mpv-danmaku"

[opencode]
src.github = "anomalyco/opencode"
fetch.github = "anomalyco/opencode"
