name: checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  packages:
    strategy:
      matrix:
        nix_path:
          - https://github.com/NixOS/nixpkgs/archive/refs/heads/nixpkgs-unstable.tar.gz
          - https://github.com/NixOS/nixpkgs/archive/refs/heads/nixos-unstable.tar.gz
          - https://github.com/NixOS/nixpkgs/archive/refs/heads/nixos-25.05.tar.gz
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@7153c2d7166d680d2c59419da714c02ce5dd0e69 # v1.8.8
        with:
          attic_token: ${{ secrets.ATTIC_TOKEN }}
          attic_cache: nur
          shell: ci

      - name: Build packages
        run: |
          nix-fast-build \
            --skip-cached \
            --no-nom \
            --override-input nixpkgs "${{ matrix.nix_path }}" \
            --flake ".#packages.$(nix eval --raw --impure --expr builtins.currentSystem)"

  flake:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@7153c2d7166d680d2c59419da714c02ce5dd0e69 # v1.8.8
        with:
          attic_token: ${{ secrets.ATTIC_TOKEN }}
          attic_cache: nur

      - name: Run flake checks
        run: nix flake check

  trigger:
    needs: [packages, flake]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger NUR update
        run: curl -XPOST "https://nur-update.nix-community.org/update?repo=trev"
