name: 'test'
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint: # make sure the action works on a clean machine without building
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          # Fetch all history, so that we can determine what hash changed
          # There might be a better way to do this.
          fetch-depth: 0
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v9
        with:
          name: nixpkgs-hammering-action

      - uses:  rmcgibbo/nixpkgs-hammering-action@master
        with:
          nixpkgs_path: ./.
          token: ${{ secrets.GITHUB_TOKEN }}
