["WeidiDeng/caddy-cloudflare-ip"]
passthru = {moduleName = "github.com/WeidiDeng/caddy-cloudflare-ip"}
fetch.github = "WeidiDeng/caddy-cloudflare-ip"
git.date_format = "%Y%m%d%H%M%S"
git.date_tz = "UTC0"
src.git = "https://github.com/WeidiDeng/caddy-cloudflare-ip.git"

["caddy-dns/cloudflare"]
passthru = {moduleName = "github.com/caddy-dns/cloudflare"}
fetch.github = "caddy-dns/cloudflare"
git.date_format = "%Y%m%d%H%M%S"
git.date_tz = "UTC0"
src.git = "https://github.com/caddy-dns/cloudflare.git"

[catppuccin-kitty]
fetch.github = "catppuccin/kitty"
src.git = "https://github.com/catppuccin/kitty.git"

[catppuccin-zsh-fsh]
fetch.github = "catppuccin/zsh-fsh"
src.git = "https://github.com/catppuccin/zsh-fsh.git"

["mholt/caddy-l4"]
passthru = {moduleName = "github.com/mholt/caddy-l4"}
fetch.github = "mholt/caddy-l4"
git.date_format = "%Y%m%d%H%M%S"
git.date_tz = "UTC0"
src.git = "https://github.com/mholt/caddy-l4.git"

["mholt/caddy-webdav"]
passthru = {moduleName = "github.com/mholt/caddy-webdav"}
fetch.github = "mholt/caddy-webdav"
git.date_format = "%Y%m%d%H%M%S"
git.date_tz = "UTC0"
src.git = "https://github.com/mholt/caddy-webdav.git"

[nix-package-versions]
fetch.github = "lazamar/nix-package-versions"
git.date_tz = "UTC0"
src.git = "https://github.com/lazamar/nix-package-versions.git"

[rime-ice]
fetch.github = "iDvel/rime-ice"
src.github_tag = "iDvel/rime-ice"
src.exclude_regex = "nightly"

[rime-ice-unstable]
fetch.github = "iDvel/rime-ice"
src.git = "https://github.com/iDvel/rime-ice.git"

[rime-moegirl]
fetch.url = "https://github.com/outloudvi/mw2fcitx/releases/download/$ver/moegirl.dict.yaml"
src.github = "outloudvi/mw2fcitx"

[yazi-rs-plugins]
fetch.github = "yazi-rs/plugins"
src.git = "https://github.com/yazi-rs/plugins.git"
