name: "npins update"
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */8 * * *' # https://crontab.guru/every-8-hours
permissions:
  contents: write
  pull-requests: write
jobs:
  npins-updater:
    name: Run npins update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=flake:nixpkgs
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set nixpkgs flake reference
        run: |
          nix registry add nixpkgs github:NixOS/nixpkgs/nixos-unstable-small
      - name: Run npins update
        run: |
          nix run nixpkgs#npins -- update
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          branch: 'npins/update'
          delete-branch: true
          commit-message: 'npins: update'
          title: 'npins: update'
          labels: auto-merge
          body: |
            - npins: update

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
      - name: Print PR number
        run: echo Pull request number is ${{ steps.update.outputs.pull-request-number }}.
