name: "Update flake inputs"
on:
  workflow_dispatch:
  schedule:
    # bump weekly at 6:50
    - cron:  '50 6 * * 1'
jobs:
  update-flake:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: "flake: update inputs"
        uses: DeterminateSystems/update-flake-lock@v19
        with:
          pr-title: "flake: update inputs"
          pr-labels: dependencies
          commit-msg: "flake: update inputs"
