env:
  CI_ALLOW_ROOT: '1'
  CI_CONFIG: ./ci/config.nix
  CI_PLATFORM: gh-actions
jobs:
  ci-check:
    name: arc-nixexprs check
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: true
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@master
    - id: ci-action-build
      name: nix build ci.gh-actions.configFile
      uses: arcnmx/ci/actions/nix/build@master
      with:
        attrs: ci.gh-actions.configFile
        out-link: .ci/workflow.yml
    - id: ci-action-compare
      name: gh-actions compare
      uses: arcnmx/ci/actions/nix/run@master
      with:
        args: -u .github/workflows/build.yml .ci/workflow.yml
        attrs: nixpkgs.diffutils
        command: diff
  stable:
    name: arc-nixexprs-stable
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: true
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@master
    - id: ci-dirty
      name: nix test dirty
      uses: arcnmx/ci/actions/nix/run@master
      with:
        attrs: ci.job.stable.run.test
        command: ci-build-dirty
        quiet: false
        stdout: ${{ runner.temp }}/ci.build.dirty
    - id: ci-test
      name: nix test build
      uses: arcnmx/ci/actions/nix/run@master
      with:
        attrs: ci.job.stable.run.test
        command: ci-build-realise
        ignore-exit-code: true
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
    - env:
        CI_EXIT_CODE: ${{ steps.ci-test.outputs.exit-code }}
      id: ci-summary
      name: nix test results
      uses: arcnmx/ci/actions/nix/run@master
      with:
        attrs: ci.job.stable.run.test
        command: ci-build-summarise
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
        stdout: ${{ runner.temp }}/ci.build.cache
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-cache
      if: always()
      name: nix test cache
      uses: arcnmx/ci/actions/nix/run@master
      with:
        attrs: ci.job.stable.run.test
        command: ci-build-cache
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.cache
  stable-mac:
    name: arc-nixexprs-stable-mac
    runs-on: macOS-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: true
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@master
    - id: ci-dirty
      name: nix test dirty
      uses: arcnmx/ci/actions/nix/run@master
      with:
        attrs: ci.job.stable-mac.run.test
        command: ci-build-dirty
        quiet: false
        stdout: ${{ runner.temp }}/ci.build.dirty
    - id: ci-test
      name: nix test build
      uses: arcnmx/ci/actions/nix/run@master
      with:
        attrs: ci.job.stable-mac.run.test
        command: ci-build-realise
        ignore-exit-code: true
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
    - env:
        CI_EXIT_CODE: ${{ steps.ci-test.outputs.exit-code }}
      id: ci-summary
      name: nix test results
      uses: arcnmx/ci/actions/nix/run@master
      with:
        attrs: ci.job.stable-mac.run.test
        command: ci-build-summarise
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
        stdout: ${{ runner.temp }}/ci.build.cache
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-cache
      if: always()
      name: nix test cache
      uses: arcnmx/ci/actions/nix/run@master
      with:
        attrs: ci.job.stable-mac.run.test
        command: ci-build-cache
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.cache
  unstable:
    name: arc-nixexprs-unstable
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: true
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@master
    - id: ci-dirty
      name: nix test dirty
      uses: arcnmx/ci/actions/nix/run@master
      with:
        attrs: ci.job.unstable.run.test
        command: ci-build-dirty
        quiet: false
        stdout: ${{ runner.temp }}/ci.build.dirty
    - id: ci-test
      name: nix test build
      uses: arcnmx/ci/actions/nix/run@master
      with:
        attrs: ci.job.unstable.run.test
        command: ci-build-realise
        ignore-exit-code: true
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
    - env:
        CI_EXIT_CODE: ${{ steps.ci-test.outputs.exit-code }}
      id: ci-summary
      name: nix test results
      uses: arcnmx/ci/actions/nix/run@master
      with:
        attrs: ci.job.unstable.run.test
        command: ci-build-summarise
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
        stdout: ${{ runner.temp }}/ci.build.cache
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-cache
      if: always()
      name: nix test cache
      uses: arcnmx/ci/actions/nix/run@master
      with:
        attrs: ci.job.unstable.run.test
        command: ci-build-cache
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.cache
  unstable-mac:
    name: arc-nixexprs-unstable-mac
    runs-on: macOS-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: true
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@master
    - id: ci-dirty
      name: nix test dirty
      uses: arcnmx/ci/actions/nix/run@master
      with:
        attrs: ci.job.unstable-mac.run.test
        command: ci-build-dirty
        quiet: false
        stdout: ${{ runner.temp }}/ci.build.dirty
    - id: ci-test
      name: nix test build
      uses: arcnmx/ci/actions/nix/run@master
      with:
        attrs: ci.job.unstable-mac.run.test
        command: ci-build-realise
        ignore-exit-code: true
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
    - env:
        CI_EXIT_CODE: ${{ steps.ci-test.outputs.exit-code }}
      id: ci-summary
      name: nix test results
      uses: arcnmx/ci/actions/nix/run@master
      with:
        attrs: ci.job.unstable-mac.run.test
        command: ci-build-summarise
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
        stdout: ${{ runner.temp }}/ci.build.cache
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-cache
      if: always()
      name: nix test cache
      uses: arcnmx/ci/actions/nix/run@master
      with:
        attrs: ci.job.unstable-mac.run.test
        command: ci-build-cache
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.cache
  unstable-nixpkgs:
    name: arc-nixexprs-unstable-nixpkgs
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: true
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@master
    - id: ci-dirty
      name: nix test dirty
      uses: arcnmx/ci/actions/nix/run@master
      with:
        attrs: ci.job.unstable-nixpkgs.run.test
        command: ci-build-dirty
        quiet: false
        stdout: ${{ runner.temp }}/ci.build.dirty
    - id: ci-test
      name: nix test build
      uses: arcnmx/ci/actions/nix/run@master
      with:
        attrs: ci.job.unstable-nixpkgs.run.test
        command: ci-build-realise
        ignore-exit-code: true
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
    - env:
        CI_EXIT_CODE: ${{ steps.ci-test.outputs.exit-code }}
      id: ci-summary
      name: nix test results
      uses: arcnmx/ci/actions/nix/run@master
      with:
        attrs: ci.job.unstable-nixpkgs.run.test
        command: ci-build-summarise
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
        stdout: ${{ runner.temp }}/ci.build.cache
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-cache
      if: always()
      name: nix test cache
      uses: arcnmx/ci/actions/nix/run@master
      with:
        attrs: ci.job.unstable-nixpkgs.run.test
        command: ci-build-cache
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.cache
  unstable-small:
    name: arc-nixexprs-unstable-small
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: true
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@master
    - id: ci-dirty
      name: nix test dirty
      uses: arcnmx/ci/actions/nix/run@master
      with:
        attrs: ci.job.unstable-small.run.test
        command: ci-build-dirty
        quiet: false
        stdout: ${{ runner.temp }}/ci.build.dirty
    - id: ci-test
      name: nix test build
      uses: arcnmx/ci/actions/nix/run@master
      with:
        attrs: ci.job.unstable-small.run.test
        command: ci-build-realise
        ignore-exit-code: true
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
    - env:
        CI_EXIT_CODE: ${{ steps.ci-test.outputs.exit-code }}
      id: ci-summary
      name: nix test results
      uses: arcnmx/ci/actions/nix/run@master
      with:
        attrs: ci.job.unstable-small.run.test
        command: ci-build-summarise
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
        stdout: ${{ runner.temp }}/ci.build.cache
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-cache
      if: always()
      name: nix test cache
      uses: arcnmx/ci/actions/nix/run@master
      with:
        attrs: ci.job.unstable-small.run.test
        command: ci-build-cache
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.cache
name: arc-nixexprs
'on':
  pull_request: {}
  push: {}
  schedule:
  - cron: 30 */2 * * *
